version: "2.1"

networks:
  zeebe_network:
    driver: bridge

services:
  application-01:
    build: .
    ports:
      - "4001:3000"
    environment:
      - INSTANCE=application-01
    links: 
      - zeebe-01
      - zeebe-02
      - zeebe-03
      - redis-01
      - redis-02
      - redis-03
      - sentinel-01
      - sentinel-02
      - sentinel-03
    depends_on:
      zeebe-01:
        condition: service_healthy
      zeebe-02:
        condition: service_healthy
      zeebe-03:
        condition: service_healthy
      redis-01:
        condition: service_healthy
      redis-02:
        condition: service_healthy
      redis-03:
        condition: service_healthy
      sentinel-01:
        condition: service_healthy
      sentinel-02:
        condition: service_healthy
      sentinel-03:
        condition: service_healthy
    networks:
      - zeebe_network
  application-02:
    build: .
    ports:
      - "4002:3000"
    environment:
      - INSTANCE=application-02
    links: 
      - zeebe-01
      - zeebe-02
      - zeebe-03
      - redis-01
      - redis-02
      - redis-03
      - sentinel-01
      - sentinel-02
      - sentinel-03
    depends_on:
      zeebe-01:
        condition: service_healthy
      zeebe-02:
        condition: service_healthy
      zeebe-03:
        condition: service_healthy
      redis-01:
        condition: service_healthy
      redis-02:
        condition: service_healthy
      redis-03:
        condition: service_healthy
      sentinel-01:
        condition: service_healthy
      sentinel-02:
        condition: service_healthy
      sentinel-03:
        condition: service_healthy
    networks:
      - zeebe_network
  application-03:
    build: .
    ports:
      - "4003:3000"
    environment:
      - INSTANCE=application-03
    links: 
      - zeebe-01
      - zeebe-02
      - zeebe-03
      - redis-01
      - redis-02
      - redis-03
      - sentinel-01
      - sentinel-02
      - sentinel-03
    depends_on:
      zeebe-01:
        condition: service_healthy
      zeebe-02:
        condition: service_healthy
      zeebe-03:
        condition: service_healthy
      redis-01:
        condition: service_healthy
      redis-02:
        condition: service_healthy
      redis-03:
        condition: service_healthy
      sentinel-01:
        condition: service_healthy
      sentinel-02:
        condition: service_healthy
      sentinel-03:
        condition: service_healthy
    networks:
      - zeebe_network
  zeebe-01:
    hostname: zeebe-01
    image: camunda/zeebe:0.20.0
    environment:
      - ZEEBE_LOG_LEVEL=debug
      - ZEEBE_NODE_ID=0
      - ZEEBE_PARTITIONS_COUNT=2
      - ZEEBE_REPLICATION_FACTOR=3
      - ZEEBE_CLUSTER_SIZE=3
      - ZEEBE_CONTACT_POINTS=zeebe-01:26502
    ports:
      - "26500:26500"
    volumes:
      - ./zeebe/zeebe.cfg.toml:/usr/local/zeebe/conf/zeebe.cfg.toml
    healthcheck:
      test: [ "CMD-SHELL", "/usr/local/zeebe/bin/zbctl status | grep -m1 -i 'Cluster size: 3' | awk 'END { if (NR==0 || $$3!='3') exit 1; exit 0;}'" ]
      interval: 3s
      timeout: 5s
      retries: 60
    networks:
      - zeebe_network
  zeebe-02:
    hostname: zeebe-02
    image: camunda/zeebe:0.20.0
    environment:
      - ZEEBE_LOG_LEVEL=debug
      - ZEEBE_NODE_ID=1
      - ZEEBE_PARTITIONS_COUNT=2
      - ZEEBE_REPLICATION_FACTOR=3
      - ZEEBE_CLUSTER_SIZE=3
      - ZEEBE_CONTACT_POINTS=zeebe-01:26502
    volumes:
      - ./zeebe/zeebe.cfg.toml:/usr/local/zeebe/conf/zeebe.cfg.toml
    healthcheck:
      test: [ "CMD-SHELL", "/usr/local/zeebe/bin/zbctl status | grep -m1 -i 'Cluster size: 3' | awk 'END { if (NR==0 || $$3!='3') exit 1; exit 0;}'" ]
      interval: 3s
      timeout: 5s
      retries: 60
    networks:
      - zeebe_network
    depends_on:
      - zeebe-01
  zeebe-03:
    hostname: zeebe-03
    image: camunda/zeebe:0.20.0
    environment:
      - ZEEBE_LOG_LEVEL=debug
      - ZEEBE_NODE_ID=2
      - ZEEBE_PARTITIONS_COUNT=2
      - ZEEBE_REPLICATION_FACTOR=3
      - ZEEBE_CLUSTER_SIZE=3
      - ZEEBE_CONTACT_POINTS=zeebe-01:26502
    volumes:
      - ./zeebe/zeebe.cfg.toml:/usr/local/zeebe/conf/zeebe.cfg.toml
    healthcheck:
      test: [ "CMD-SHELL", "/usr/local/zeebe/bin/zbctl status | grep -m1 -i 'Cluster size: 3' | awk 'END { if (NR==0 || $$3!='3') exit 1; exit 0;}'" ]
      interval: 3s
      timeout: 5s
      retries: 60
    networks:
      - zeebe_network
    depends_on:
      - zeebe-02
  redis-01:
    image: "healthcheck/redis"
    mem_limit: 1024m
    healthcheck:
      interval: 1s
      retries: 30
    volumes:
      - ./redis/node-01/redis.conf:/redis.conf
    command: redis-server /redis.conf
    networks:
      - zeebe_network
  redis-02:
    image: "healthcheck/redis"
    mem_limit: 1024m
    healthcheck:
      interval: 1s
      retries: 30
    volumes:
      - ./redis/node-02/redis.conf:/redis.conf
    command: redis-server /redis.conf
    networks:
      - zeebe_network
  redis-03:
    image: "healthcheck/redis"
    mem_limit: 1024m
    healthcheck:
      interval: 1s
      retries: 30
    volumes:
      - ./redis/node-03/redis.conf:/redis.conf
    command: redis-server /redis.conf
    networks:
      - zeebe_network
  sentinel-01:
    image: "healthcheck/redis"
    mem_limit: 1024m
    healthcheck:
      interval: 1s
      retries: 30
    volumes:
      - ./redis/node-01/sentinel.conf:/sentinel.conf
    command: redis-server /sentinel.conf --sentinel
    networks:
      - zeebe_network
  sentinel-02:
    image: "healthcheck/redis"
    mem_limit: 1024m
    healthcheck:
      interval: 1s
      retries: 30
    volumes:
      - ./redis/node-02/sentinel.conf:/sentinel.conf
    command: redis-server /sentinel.conf --sentinel
    networks:
      - zeebe_network
  sentinel-03:
    image: "healthcheck/redis"
    mem_limit: 1024m
    healthcheck:
      interval: 1s
      retries: 30
    volumes:
      - ./redis/node-03/sentinel.conf:/sentinel.conf
    command: redis-server /sentinel.conf --sentinel
    networks:
      - zeebe_network